# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['fun_print', 'fool_print']

# %% ../00_core.ipynb 3
def fun_print(): print('fun') 

# %% ../00_core.ipynb 4
def fool_print(): print('fool') 
