# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'fun_print']

# %% ../00_core.ipynb 3
def foo(): pass

# %% ../00_core.ipynb 4
def fun_print(): print('fun') 
